/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fangzhangmnm (https://sketchfab.com/fangzhangmnm)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/modern-furniture-pack-11bd2dcb9ec14142bc92968c2a85c029
title: Modern Furniture Pack
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/modern_furniture.gltf')
  return (
    <group ref={group} {...props} dispose={null} position={[0,0,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
            <group position={[0.02, 0.08, 0.57]}>
              <mesh geometry={nodes.Quint_FabricFlower_0.geometry} material={nodes.Quint_FabricFlower_0.material} />
              <mesh geometry={nodes.Quint_FabricGrey_0.geometry} material={nodes.Quint_FabricGrey_0.material} />
            </group>
            <group position={[0.34, -0.84, 0.53]}>
              <mesh
                geometry={nodes.Plane001_FabricFlower_0.geometry}
                material={nodes.Plane001_FabricFlower_0.material}
              />
            </group>
            <group position={[1.97, -2.16, 0.5]} rotation={[-0.43, 0.34, -0.56]}>
              <mesh
                geometry={nodes.Plane003_FabricOrange_0.geometry}
                material={nodes.Plane003_FabricOrange_0.material}
              />
            </group>
            <group position={[-0.36, -0.84, 0.53]}>
              <mesh
                geometry={nodes.Plane002_FabricFlower_0.geometry}
                material={nodes.Plane002_FabricFlower_0.material}
              />
            </group>
            <mesh geometry={nodes.Bed_FabricWhite_0.geometry} material={nodes.Bed_FabricWhite_0.material} />
            <mesh geometry={nodes.Bed_Wood_0.geometry} material={nodes.Bed_Wood_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1, 1, 1]}>
            <mesh geometry={nodes.Chair1_FabricGrey_0.geometry} material={nodes.Chair1_FabricGrey_0.material} />
            <mesh geometry={nodes.Chair1_Wood_0.geometry} material={nodes.Chair1_Wood_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Desk_PaintWhite_0.geometry} material={nodes.Desk_PaintWhite_0.material} />
            <mesh geometry={nodes.Desk_SteelBlack_0.geometry} material={nodes.Desk_SteelBlack_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Kitchen1_Wood_0.geometry} material={nodes.Kitchen1_Wood_0.material} />
            <mesh geometry={nodes.Kitchen1_Marble_0.geometry} material={nodes.Kitchen1_Marble_0.material} />
            <mesh geometry={nodes.Kitchen1_SteelSilver_0.geometry} material={nodes.Kitchen1_SteelSilver_0.material} />
            <mesh geometry={nodes.Kitchen1_CeramicWhite_0.geometry} material={nodes.Kitchen1_CeramicWhite_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[506.32, 506.32, 506.32]}>
            <mesh geometry={nodes.Floor_Concrete_0.geometry} material={materials.Concrete} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Sofa1_FabricOrange_0.geometry} material={nodes.Sofa1_FabricOrange_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Sofa2_FabricGrey_0.geometry} material={nodes.Sofa2_FabricGrey_0.material} />
          </group>
          <group position={[0,0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Table_Wood_0.geometry} material={nodes.Table_Wood_0.material} />
          </group>
          <group position={[-261.54, 88.87, 380.84]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Monitor_PlasticBlack_0.geometry} material={nodes.Monitor_PlasticBlack_0.material} />
          </group>
          <group position={[-262.12, 88.87, 407.64]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Keyboard_Keyboard_0.geometry} material={materials.Keyboard} />
          </group>
          <group position={[-216.12, 88.87, 413.47]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Mouse_PlasticBlack_0.geometry} material={nodes.Mouse_PlasticBlack_0.material} />
          </group>
          <group position={[350.71, 0.02, 803.55]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Toilet_CeramicWhite_0.geometry} material={nodes.Toilet_CeramicWhite_0.material} />
          </group>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Lamp2_SteelBlack_0.geometry} material={nodes.Lamp2_SteelBlack_0.material} />
            <mesh geometry={nodes.Lamp2_LightsYellow_0.geometry} material={nodes.Lamp2_LightsYellow_0.material} />
          </group>
          <group position={[-61.16, 323.27, 809.59]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Light1_LightsWhite_0.geometry} material={nodes.Light1_LightsWhite_0.material} />
            <mesh geometry={nodes.Light1_SteelBlack_0.geometry} material={nodes.Light1_SteelBlack_0.material} />
          </group>
          <group position={[-61.16, 0, 809.59]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Lamp3_LightsYellow_0.geometry} material={nodes.Lamp3_LightsYellow_0.material} />
            <mesh geometry={nodes.Lamp3_PlasticBlack_0.geometry} material={nodes.Lamp3_PlasticBlack_0.material} />
          </group>
          <group position={[-161.68, 268.68, 809.59]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Light2_LightsYellow_0.geometry} material={nodes.Light2_LightsYellow_0.material} />
            <mesh geometry={nodes.Light2_SteelBlack_0.geometry} material={nodes.Light2_SteelBlack_0.material} />
          </group>
          <group position={[-118.56, 0.02, 812.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Lamp4_LightsYellow_0.geometry} material={nodes.Lamp4_LightsYellow_0.material} />
            <mesh geometry={nodes.Lamp4_SteelBlack_0.geometry} material={nodes.Lamp4_SteelBlack_0.material} />
          </group>
          <group position={[-203.01, 0.02, 812.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Lamp5_SteelBlack_0.geometry} material={nodes.Lamp5_SteelBlack_0.material} />
            <mesh geometry={nodes.Lamp5_LightsWhite_0.geometry} material={nodes.Lamp5_LightsWhite_0.material} />
          </group>
          <group position={[-349.96, 88.87, 387.29]} rotation={[-Math.PI / 2, 0, 0.55]} scale={[1,1,1]}>
            <mesh geometry={nodes.Lamp1_SteelBlack_0.geometry} material={nodes.Lamp1_SteelBlack_0.material} />
            <mesh geometry={nodes.Lamp1_LightsWhite_0.geometry} material={nodes.Lamp1_LightsWhite_0.material} />
          </group>
          <group position={[478.61, -0.01, 811.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Shower_Tile_0.geometry} material={materials.Tile} />
            <mesh geometry={nodes.Shower_SteelSilver_0.geometry} material={nodes.Shower_SteelSilver_0.material} />
            <mesh geometry={nodes.Shower_PlasticCurtain_0.geometry} material={materials.PlasticCurtain} />
          </group>
          <group position={[-260.13, 268.68, 809.59]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Light3_SteelBlack_0.geometry} material={nodes.Light3_SteelBlack_0.material} />
            <mesh geometry={nodes.Light3_LightsWhite_0.geometry} material={nodes.Light3_LightsWhite_0.material} />
          </group>
          <group position={[-443.15, 0.02, 659.76]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Counter1_PaintWhite_0.geometry} material={nodes.Counter1_PaintWhite_0.material} />
            <mesh geometry={nodes.Counter1_Marble_0.geometry} material={nodes.Counter1_Marble_0.material} />
            <mesh geometry={nodes.Counter1_PlasticBlack_0.geometry} material={nodes.Counter1_PlasticBlack_0.material} />
          </group>
          <group position={[-453.43, 115.29, 656.66]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Cashier_PlasticBlack_0.geometry} material={nodes.Cashier_PlasticBlack_0.material} />
          </group>
          <group position={[500.92, 0.01, 600.26]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.TVDesk_Wood_0.geometry} material={nodes.TVDesk_Wood_0.material} />
          </group>
          <group position={[511.75, 42.91, 598.64]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.TV_PlasticBlack_0.geometry} material={nodes.TV_PlasticBlack_0.material} />
          </group>
          <group position={[562.05, 0.05, 692.61]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.Curtain001_FabricFlower_0.geometry}
              material={nodes.Curtain001_FabricFlower_0.material}
            />
          </group>
          <group position={[562.05, 0.05, 528.12]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Curtain_FabricFlower_0.geometry} material={nodes.Curtain_FabricFlower_0.material} />
          </group>
          <group position={[561.74, -0.02, 385.32]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Door_Wood_0.geometry} material={nodes.Door_Wood_0.material} />
            <mesh geometry={nodes.Door_SteelSilver_0.geometry} material={nodes.Door_SteelSilver_0.material} />
          </group>
          <group position={[283.59, 0.02, 823.17]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Sink_CeramicWhite_0.geometry} material={nodes.Sink_CeramicWhite_0.material} />
            <mesh geometry={nodes.Sink_SteelSilver_0.geometry} material={nodes.Sink_SteelSilver_0.material} />
          </group>
          <group position={[283.59, 172.67, 857.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Mirror_SteelBlack_0.geometry} material={nodes.Mirror_SteelBlack_0.material} />
            <mesh geometry={nodes.Mirror_Mirror_0.geometry} material={materials.Mirror} />
          </group>
          <group position={[-548.83, 0, 565.17]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Chair2_SteelSilver_0.geometry} material={nodes.Chair2_SteelSilver_0.material} />
            <mesh geometry={nodes.Chair2_FabricWhite_0.geometry} material={nodes.Chair2_FabricWhite_0.material} />
          </group>
          <group position={[-452.44, 0.01, 821.1]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Cube_SteelHair_0.geometry} material={materials.SteelHair} />
            <mesh geometry={nodes.Cube_SteelSilver_0.geometry} material={nodes.Cube_SteelSilver_0.material} />
          </group>
          <group position={[-297.38, 0.01, 658.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Baker_SteelSilver_0.geometry} material={nodes.Baker_SteelSilver_0.material} />
            <mesh geometry={nodes.Baker_SteelBlack_0.geometry} material={nodes.Baker_SteelBlack_0.material} />
          </group>
          <group position={[-774.73, 150, 444.31]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.GlassPanelPillar_SteelSilver_0.geometry}
              material={nodes.GlassPanelPillar_SteelSilver_0.material}
            />
          </group>
          <group position={[-774.73, 150, 494.31]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[1,1,1]}>
            <mesh geometry={nodes.GlassPanel_Glass_0.geometry} material={materials.Glass} />
            <mesh
              geometry={nodes.GlassPanel_SteelSilver_0.geometry}
              material={nodes.GlassPanel_SteelSilver_0.material}
            />
          </group>
          <group position={[0.45, 0.01, 817.01]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Light4_SteelSilver_0.geometry} material={nodes.Light4_SteelSilver_0.material} />
            <mesh geometry={nodes.Light4_LightsWhite_0.geometry} material={nodes.Light4_LightsWhite_0.material} />
          </group>
          <group position={[-518.09, 0.05, 451.64]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Shelf_Wood_0.geometry} material={nodes.Shelf_Wood_0.material} />
          </group>
          <group position={[-571.69, 121.69, 468.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Vase1_Marble_0.geometry} material={nodes.Vase1_Marble_0.material} />
          </group>
          <group position={[-504.36, 81.58, 468.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Vase2_Marble_0.geometry} material={nodes.Vase2_Marble_0.material} />
          </group>
          <group position={[-548.29, 121.69, 467.76]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Book_Book_0.geometry} material={nodes.Book_Book_0.material} />
          </group>
          <group position={[-512.42, 121.69, 470.81]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <group position={[0.22, 0.02, 0]} scale={[0.93, 0.93, 0.93]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|_Book_0'].material}
              />
            </group>
            <group position={[-0.19, -0.01, 0]} scale={0.83}>
              <mesh
                geometry={nodes['Books|Book|Dupli|1_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|1_Book_0'].material}
              />
            </group>
            <group position={[-0.14, 0.02, 0]} scale={[0.97, 0.97, 0.97]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|2_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|2_Book_0'].material}
              />
            </group>
            <group position={[-0.09, 0.02, 0]} scale={[0.86, 0.86, 0.86]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|3_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|3_Book_0'].material}
              />
            </group>
            <group position={[-0.03, -0.01, 0]} scale={[0.96, 0.96, 0.96]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|4_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|4_Book_0'].material}
              />
            </group>
            <group position={[0.01, 0.02, 0]} scale={[0.98, 0.98, 0.98]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|5_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|5_Book_0'].material}
              />
            </group>
            <group position={[0.14, 0.02, 0]} scale={0.87}>
              <mesh
                geometry={nodes['Books|Book|Dupli|6_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|6_Book_0'].material}
              />
            </group>
            <group position={[0.12, -0.01, 0]} scale={[0.88, 0.88, 0.88]}>
              <mesh
                geometry={nodes['Books|Book|Dupli|7_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|7_Book_0'].material}
              />
            </group>
            <group position={[0.09, 0.02, 0]} scale={0.88}>
              <mesh
                geometry={nodes['Books|Book|Dupli|8_Book_0'].geometry}
                material={nodes['Books|Book|Dupli|8_Book_0'].material}
              />
            </group>
            <mesh geometry={nodes.Books_Book_0.geometry} material={nodes.Books_Book_0.material} />
          </group>
          <group position={[-668.32, -0.01, 434.66]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Plane_Wood_0.geometry} material={nodes.Plane_Wood_0.material} />
          </group>
          <group position={[165.55, 33.71, 458.75]} rotation={[-1.99, 0.3, -0.7]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.Cushion1_FabircPatterns_0.geometry}
              material={nodes.Cushion1_FabircPatterns_0.material}
            />
          </group>
          <group position={[218.81, 29.11, 458.61]} rotation={[-1.72, 0.01, 0.17]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.Cushion3_FabircPatterns_0.geometry}
              material={nodes.Cushion3_FabircPatterns_0.material}
            />
          </group>
          <group position={[324.84, 31.45, 468.82]} rotation={[-2.08, 0.19, -0.04]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.Cushion4_FabircPatterns_0.geometry}
              material={nodes.Cushion4_FabircPatterns_0.material}
            />
          </group>
          <group position={[279.23, 34.11, 480.7]} rotation={[-2.29, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Cushion2_FabircPatterns_0.geometry}
              material={nodes.Cushion2_FabircPatterns_0.material}
            />
          </group>
          <group position={[158.07, 25.75, 399.3]} rotation={[-1.63, 0.28, 1.71]} scale={[1,1,1]}>
            <mesh
              geometry={nodes.Cushion5_FabircPatterns_0.geometry}
              material={nodes.Cushion5_FabircPatterns_0.material}
            />
          </group>
          <group position={[322.13, -0.01, 344.54]} rotation={[-Math.PI / 2, 0, 0]} scale={[1,1,1]}>
            <mesh geometry={nodes.Carpet_FabircPatterns_0.geometry} material={nodes.Carpet_FabircPatterns_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modern_furniture.gltf')
