/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3D Share (https://sketchfab.com/3dsharesg)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/2163e14e9b8c427698e8aa80923a6241
title: Samsung Series 9 Notebook 1768
*/
// import React from 'react'
import * as THREE from 'three'
import ReactDOM from 'react-dom'
// import { Canvas, extend, useThree } from 'react-three-fiber'
import { DragControls } from 'three/examples/jsm/controls/DragControls'
// import './styles.css'


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import {extend,useThree} from '@react-three/fiber'

// import { DragControls } from 'three/examples/jsm/controls/DragControls'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/notebook.gltf')

  const Model = () =>{
    return (
      <group ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-7.82, -8.7, -7.66]}>
              <mesh geometry={nodes.mesh_0.geometry} material={materials.Material__64} />
            </group>
          </group>
        </group>
      </group>
    )      
  }

  return (
    <>
    <dragControls args={[[ex]],camera,domElement} />
  </>
  )
}

useGLTF.preload('/notebook.gltf')
