/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: NTSC (https://sketchfab.com/NTSC)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/pool-table-set-7a91611c0e5d4f519c9e7cd1425d066a
title: Pool Table Set
*/
import ReactDOM from "react-dom";
import React, { Suspense, useEffect, useRef } from "react";
import { useLoader } from "@react-three/fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { Controls, useControl } from "react-three-gui";
import { OrbitControls, TransformControls } from "@react-three/drei";

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";


export default function Model({ edit, onNOff }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/billiard.gltf')

  const orbit = useRef();
  const transform = useRef();
  const mode = useControl("mode", {
    type: "select",
    items: ["rotate", "translate"],
  });
  useEffect(() => {

  });
  return (
    <>
    {onNOff ? 
      <TransformControls ref={transform} showZ={edit} showY={edit} showX={edit}>
    <group ref={group}  dispose={null} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['PoolTable_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
          </group>
          <group position={[23038.68, 10898.37, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.GeoSphere01_White_0.geometry} material={materials.White} />
          </group>
          <group position={[-27682.97, 10898.37, -559.28]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere002_Ball13_0.geometry} material={materials.Ball13} />
          </group>
          <group position={[-27682.97, 10898.37, 4286.15]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere003_Ball14_0.geometry} material={materials.Ball14} />
          </group>
          <group position={[-27682.97, 10898.37, 9239.61]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere004_Ball15_0.geometry} material={materials.Ball15} />
          </group>
          <group position={[-27682.97, 10898.37, -5421.93]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere005_Ball12_0.geometry} material={materials.Ball12} />
          </group>
          <group position={[-27682.97, 10898.37, -10259.84]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere006_Ball11_0.geometry} material={materials.Ball11} />
          </group>
          <group position={[-23460.66, 10898.37, -7917.78]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere008_Ball10_0.geometry} material={materials.Ball10} />
          </group>
          <group position={[-23460.66, 10898.37, -3004]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere009_Ball9_0.geometry} material={materials.Ball9} />
          </group>
          <group position={[-23460.66, 10898.37, 1833.9]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere010_Ball7_0.geometry} material={materials.Ball7} />
          </group>
          <group position={[-23460.66, 10898.37, 6696.56]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere011_Ball6_0.geometry} material={materials.Ball6} />
          </group>
          <group position={[-18808.11, 10898.37, -5439.24]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere012_Ball4_0.geometry} material={materials.Ball4} />
          </group>
          <group position={[-18808.11, 10898.37, -525.45]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere013_Ball8_0.geometry} material={materials.Ball8} />
          </group>
          <group position={[-18808.11, 10898.37, 4312.45]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere014_Ball5_0.geometry} material={materials.Ball5} />
          </group>
          <group position={[-14447.74, 10898.37, -2934.28]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere015_Ball3_0.geometry} material={materials.Ball3} />
          </group>
          <group position={[-14447.74, 10898.37, 1979.5]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere016_Ball2_0.geometry} material={materials.Ball2} />
          </group>
          <group position={[-10053.97, 10898.37, -477.39]} rotation={[2.69, 0.56, 1.75]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.GeoSphere017_Ball1_0.geometry} material={materials.Ball1} />
          </group>
          <group position={[33430.34, 11043.84, -24531.32]} rotation={[0.07, -0.8, 1.62]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Cylinder01_Table_0.geometry} material={materials.Table} />
          </group>
        </group>
      </group>
    </group>
          </TransformControls> : <></>}
          </>

  )
}

useGLTF.preload('/billiard.gltf')
