/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: jfarstrider (https://sketchfab.com/jfarstrider)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-furniture-set-b0460bf511fa4c659d57f4f6df0e65a9
title: Low Poly Furniture Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/furnitures.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[2, 1, 2]}>
            <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
          </group>
          <group position={[-0.59, 0, -0.73]}>
            <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
          </group>
          <group position={[4.3, 0.35, 3.67]}>
            <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
            <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
          </group>
          <group position={[5.56, 0.2, 0.36]}>
            <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} />
            <mesh geometry={nodes.Object_12.geometry} material={nodes.Object_12.material} />
          </group>
          <group position={[6.53, 0.71, 0.7]} rotation={[-1.59, 0.82, 1.6]}>
            <mesh geometry={nodes.Object_14.geometry} material={nodes.Object_14.material} />
            <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} />
          </group>
          <group position={[1.62, 1, -4.64]} rotation={[0.1, 0.17, -0.2]}>
            <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} />
            <mesh geometry={nodes.Object_18.geometry} material={nodes.Object_18.material} />
          </group>
          <group position={[1.6, 1, -4.64]} rotation={[0.1, 0.17, -0.2]}>
            <mesh geometry={nodes.Object_20.geometry} material={nodes.Object_20.material} />
            <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} />
          </group>
          <group position={[1.57, 1, -4.64]} rotation={[0.1, 0.17, -0.2]}>
            <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} />
            <mesh geometry={nodes.Object_24.geometry} material={nodes.Object_24.material} />
          </group>
          <group position={[1.52, 1.01, -4.64]} rotation={[0.12, 0.16, -0.32]}>
            <mesh geometry={nodes.Object_26.geometry} material={nodes.Object_26.material} />
            <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} />
          </group>
          <group position={[1.36, 1, -4.64]} rotation={[0, 0, -0.25]}>
            <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} />
            <mesh geometry={nodes.Object_30.geometry} material={nodes.Object_30.material} />
          </group>
          <group position={[1.47, 0.97, -4.62]} rotation={[0, 0, -0.38]}>
            <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
            <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
          </group>
          <group position={[1.45, 0.97, -4.62]} rotation={[0, 0, -0.35]}>
            <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
            <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
          </group>
          <group position={[1.42, 0.97, -4.62]} rotation={[0, 0, -0.38]}>
            <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
            <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
          </group>
          <group position={[1.17, 0.6, -4.71]}>
            <mesh geometry={nodes.Object_41.geometry} material={nodes.Object_41.material} />
          </group>
          <group position={[-0.67, 0.6, -2.61]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_43.geometry} material={nodes.Object_43.material} />
          </group>
          <group position={[1.83, 0.74, -2.72]}>
            <mesh geometry={nodes.Object_45.geometry} material={nodes.Object_45.material} />
          </group>
          <group position={[2.25, 0.69, -2.7]} scale={0.48}>
            <mesh geometry={nodes.Object_47.geometry} material={nodes.Object_47.material} />
          </group>
          <group position={[1.82, 0.02, -2.72]}>
            <mesh geometry={nodes.Object_49.geometry} material={nodes.Object_49.material} />
            <mesh geometry={nodes.Object_50.geometry} material={nodes.Object_50.material} />
            <mesh geometry={nodes.Object_51.geometry} material={nodes.Object_51.material} />
          </group>
          <group position={[1.2, 0.15, 3.69]}>
            <mesh geometry={nodes.Object_53.geometry} material={nodes.Object_53.material} />
            <mesh geometry={nodes.Object_54.geometry} material={nodes.Object_54.material} />
          </group>
          <group position={[2.65, 0.45, -3.37]} rotation={[0, -0.92, 0]}>
            <mesh geometry={nodes.Object_56.geometry} material={nodes.Object_56.material} />
            <mesh geometry={nodes.Object_57.geometry} material={nodes.Object_57.material} />
          </group>
          <group position={[3.99, -0.01, -2.68]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_59.geometry} material={nodes.Object_59.material} />
            <mesh geometry={nodes.Object_60.geometry} material={nodes.Object_60.material} />
          </group>
          <group position={[1.85, -0.01, 0]}>
            <mesh geometry={nodes.Object_62.geometry} material={nodes.Object_62.material} />
            <mesh geometry={nodes.Object_63.geometry} material={nodes.Object_63.material} />
          </group>
          <group position={[-3.8, 1.23, 2.9]}>
            <mesh geometry={nodes.Object_65.geometry} material={nodes.Object_65.material} />
            <mesh geometry={nodes.Object_66.geometry} material={nodes.Object_66.material} />
          </group>
          <group position={[-0.21, 0.9, -4.11]} scale={[1, 1.16, 1]}>
            <mesh geometry={nodes.Object_68.geometry} material={nodes.Object_68.material} />
            <mesh geometry={nodes.Object_69.geometry} material={nodes.Object_69.material} />
          </group>
          <group position={[3.98, 0.75, -4.72]}>
            <mesh geometry={nodes.Object_71.geometry} material={nodes.Object_71.material} />
            <mesh geometry={nodes.Object_72.geometry} material={nodes.Object_72.material} />
            <mesh geometry={nodes.Object_73.geometry} material={nodes.Object_73.material} />
          </group>
          <group position={[6.59, 0.28, 1.61]}>
            <mesh geometry={nodes.Object_75.geometry} material={nodes.Object_75.material} />
            <mesh geometry={nodes.Object_76.geometry} material={nodes.Object_76.material} />
            <mesh geometry={nodes.Object_77.geometry} material={nodes.Object_77.material} />
          </group>
          <group position={[1.14, 0.71, -4.64]} rotation={[-0.37, 0, 0]}>
            <mesh geometry={nodes.Object_79.geometry} material={nodes.Object_79.material} />
            <mesh geometry={nodes.Object_80.geometry} material={nodes.Object_80.material} />
            <mesh geometry={nodes.Object_81.geometry} material={nodes.Object_81.material} />
            <mesh geometry={nodes.Object_82.geometry} material={nodes.Object_82.material} />
            <mesh geometry={nodes.Object_83.geometry} material={nodes.Object_83.material} />
          </group>
          <group position={[1.41, 0.41, -4.64]} rotation={[-0.34, 0.03, Math.PI / 2]}>
            <mesh geometry={nodes.Object_85.geometry} material={nodes.Object_85.material} />
            <mesh geometry={nodes.Object_86.geometry} material={nodes.Object_86.material} />
            <mesh geometry={nodes.Object_87.geometry} material={nodes.Object_87.material} />
            <mesh geometry={nodes.Object_88.geometry} material={nodes.Object_88.material} />
            <mesh geometry={nodes.Object_89.geometry} material={nodes.Object_89.material} />
          </group>
          <group position={[-2.27, 0.69, 2.83]}>
            <mesh geometry={nodes.Object_91.geometry} material={nodes.Object_91.material} />
            <mesh geometry={nodes.Object_92.geometry} material={nodes.Object_92.material} />
          </group>
          <group position={[2.23, 0.7, -2.47]}>
            <mesh geometry={nodes.Object_94.geometry} material={nodes.Object_94.material} />
          </group>
          <group position={[-7.16, 0.32, 2.96]}>
            <mesh geometry={nodes.Object_96.geometry} material={nodes.Object_96.material} />
            <mesh geometry={nodes.Object_97.geometry} material={nodes.Object_97.material} />
          </group>
          <group position={[-6.12, 0.53, 2.86]}>
            <mesh geometry={nodes.Object_99.geometry} material={nodes.Object_99.material} />
          </group>
          <group position={[1.01, 1.11, 2.69]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_101.geometry} material={nodes.Object_101.material} />
            <mesh geometry={nodes.Object_102.geometry} material={nodes.Object_102.material} />
          </group>
          <group position={[-5.53, 0.31, 2.89]}>
            <mesh geometry={nodes.Object_104.geometry} material={nodes.Object_104.material} />
            <mesh geometry={nodes.Object_105.geometry} material={nodes.Object_105.material} />
            <mesh geometry={nodes.Object_106.geometry} material={nodes.Object_106.material} />
          </group>
          <group position={[2.69, 0.5, -0.04]} rotation={[-1.13, 0.34, 0.76]}>
            <mesh geometry={nodes.Object_108.geometry} material={nodes.Object_108.material} />
            <mesh geometry={nodes.Object_109.geometry} material={nodes.Object_109.material} />
          </group>
          <group position={[-0.6, 0.56, -0.72]} rotation={[-0.36, 0.18, -0.89]}>
            <mesh geometry={nodes.Object_111.geometry} material={nodes.Object_111.material} />
            <mesh geometry={nodes.Object_112.geometry} material={nodes.Object_112.material} />
          </group>
          <group position={[0, 1.07, 2.88]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_114.geometry} material={nodes.Object_114.material} />
            <mesh geometry={nodes.Object_115.geometry} material={nodes.Object_115.material} />
            <mesh geometry={nodes.Object_116.geometry} material={nodes.Object_116.material} />
            <mesh geometry={nodes.Object_117.geometry} material={nodes.Object_117.material} />
            <mesh geometry={nodes.Object_118.geometry} material={nodes.Object_118.material} />
          </group>
          <group position={[5.3, 0.05, 2.52]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_120.geometry} material={nodes.Object_120.material} />
            <mesh geometry={nodes.Object_121.geometry} material={nodes.Object_121.material} />
            <mesh geometry={nodes.Object_122.geometry} material={nodes.Object_122.material} />
          </group>
          <group position={[5.93, 0.01, -2.73]}>
            <mesh geometry={nodes.Object_124.geometry} material={nodes.Object_124.material} />
            <mesh geometry={nodes.Object_125.geometry} material={nodes.Object_125.material} />
          </group>
          <group position={[6.57, 0.76, 1.61]}>
            <mesh geometry={nodes.Object_127.geometry} material={nodes.Object_127.material} />
            <mesh geometry={nodes.Object_128.geometry} material={nodes.Object_128.material} />
          </group>
          <group position={[5.07, 0.75, -4.7]}>
            <mesh geometry={nodes.Object_130.geometry} material={nodes.Object_130.material} />
            <mesh geometry={nodes.Object_131.geometry} material={nodes.Object_131.material} />
          </group>
          <group position={[1.84, 0.63, -2.73]}>
            <mesh geometry={nodes.Object_133.geometry} material={nodes.Object_133.material} />
            <mesh geometry={nodes.Object_134.geometry} material={nodes.Object_134.material} />
          </group>
          <group position={[-3.81, 0.35, 2.84]}>
            <mesh geometry={nodes.Object_136.geometry} material={nodes.Object_136.material} />
            <mesh geometry={nodes.Object_137.geometry} material={nodes.Object_137.material} />
            <mesh geometry={nodes.Object_138.geometry} material={nodes.Object_138.material} />
          </group>
          <group position={[1.87, 0.58, 1.47]}>
            <mesh geometry={nodes.Object_140.geometry} material={nodes.Object_140.material} />
            <mesh geometry={nodes.Object_141.geometry} material={nodes.Object_141.material} />
            <mesh geometry={nodes.Object_142.geometry} material={nodes.Object_142.material} />
          </group>
          <group position={[1.87, 0.48, 1.48]}>
            <mesh geometry={nodes.Object_144.geometry} material={nodes.Object_144.material} />
            <mesh geometry={nodes.Object_145.geometry} material={nodes.Object_145.material} />
          </group>
          <group position={[0.11, 0.33, 0.25]}>
            <mesh geometry={nodes.Object_147.geometry} material={nodes.Object_147.material} />
            <mesh geometry={nodes.Object_148.geometry} material={nodes.Object_148.material} />
            <mesh geometry={nodes.Object_149.geometry} material={nodes.Object_149.material} />
            <mesh geometry={nodes.Object_150.geometry} material={nodes.Object_150.material} />
          </group>
          <group position={[5.77, 0.33, 3.67]}>
            <mesh geometry={nodes.Object_152.geometry} material={nodes.Object_152.material} />
            <mesh geometry={nodes.Object_153.geometry} material={nodes.Object_153.material} />
            <mesh geometry={nodes.Object_154.geometry} material={nodes.Object_154.material} />
          </group>
          <group position={[-1.37, 0.35, 2.83]}>
            <mesh geometry={nodes.Object_156.geometry} material={nodes.Object_156.material} />
            <mesh geometry={nodes.Object_157.geometry} material={nodes.Object_157.material} />
            <mesh geometry={nodes.Object_158.geometry} material={nodes.Object_158.material} />
          </group>
          <group position={[1.98, 0.07, 3.77]}>
            <mesh geometry={nodes.Object_160.geometry} material={nodes.Object_160.material} />
            <mesh geometry={nodes.Object_161.geometry} material={nodes.Object_161.material} />
          </group>
          <group position={[3.15, 0.35, 3.69]} rotation={[Math.PI, 0, Math.PI]}>
            <mesh geometry={nodes.Object_163.geometry} material={nodes.Object_163.material} />
            <mesh geometry={nodes.Object_164.geometry} material={nodes.Object_164.material} />
            <mesh geometry={nodes.Object_165.geometry} material={nodes.Object_165.material} />
          </group>
          <group position={[3.01, 1.13, -4.71]}>
            <mesh geometry={nodes.Object_167.geometry} material={nodes.Object_167.material} />
            <mesh geometry={nodes.Object_168.geometry} material={nodes.Object_168.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/furnitures.gltf')
